[package]
name = "foundation-wave-1-candidate-consumer"
version = "0.0.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
moenarch-runtime-core = "=0.2.1"
moenarch-runtime-onnx = "=0.1.1"
moenarch-jobs-core = "=0.1.2"
moenarch-math-geometry-2d = "=0.1.1"
moenarch-numbers-core = "=0.1.1"
moenarch-tensor-data = "=0.1.1"
moenarch-vector-analysis-core = "=0.1.1"
moenarch-data-inversion-core = "=0.1.1"
moenarch-model-runtime = "=0.1.1"
moenarch-math-linear = "=0.1.1"
moenarch-math-signal-core = "=0.1.1"
moenarch-vector-analysis-index = "=0.1.1"
moenarch-math-sparse-data = "=0.1.1"
moenarch-media-core = "=0.1.0"
